### PR TITLE
added lit-html dependency

### PR DESCRIPTION
**Pull request by gmblpnw**

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
lit 2 already includes lit-html as dependency, why do you need it separately?

**Comment by gmblpnw** [comment]
Apologies.  It looks like I was running pnpm install instead of npm install.  With pnpm I get errors indicating that lit-html depedencies are missing.  That is not the case when I run npm install.  I'll withdraw the pull request.

**Comment by alfonsogarciacaro** [comment]
Interesting, I would think that pnpm resolves transitive dependencies the same way as npm does, but maybe there was a glitch. Thanks a lot for the explanation!

**Comment by gmblpnw** [comment]
Yeah.  Unfortunately I'm a bit new to this area and so I don't have the
depth to provide much insight.  I noticed that the Fable.Lit.Templates were
including lit-html ( Fable.Lit.Templates/package.json 
<https://github.com/AngelMunoz/Fable.Lit.Templates/blob/main/templates/elmish-lit/package.json>)
and so I thought that the missing dep might be the issue.

**Comment by alfonsogarciacaro** [comment]
Sorry @gmblpnw, I got a similar report and I think I finally understand what's happening :) See https://github.com/alfonsogarciacaro/Lit.TodoMVC/issues/5#issuecomment-974912312

**Comment by gmblpnw** [comment]
Thanks for the heads up.  That's exactly the error I was getting.  Lesson for me is to be more thorough in reporting the error! :)

**Pull request closed without merging**
